from __future__ import annotations

from collections.abc import Callable, Sequence
from contextlib import AbstractContextManager
from datetime import datetime
from typing import Any, Protocol
from uuid import UUID

from pydantic import BaseModel

from simon.domain.accounts import ManagedAccount
from simon.domain.connected_tools import ActionProposal, GoogleConnection, GoogleOAuthState
from simon.domain.context import ExplicitMemory, RecallDocument
from simon.domain.conversations import Message, ModelAttempt, Run, RunEvent, Thread
from simon.domain.identity import (
    Challenge,
    Enrollment,
    Membership,
    Passkey,
    PasswordCredential,
    Session,
)
from simon.domain.interaction import ResponsePreferences, RunFeedback
from simon.domain.models import (
    AuditEvent,
    CapabilityDefinition,
    Job,
    JobStatus,
    OutboxEvent,
)
from simon.domain.project_files import ProjectDrive, ProjectFileOperation
from simon.domain.tasks import ProjectArtifact
from simon.domain.voice import VoiceSession

CapabilityHandler = Callable[[BaseModel], dict[str, Any]]


class CapabilityStore(Protocol):
    def register(
        self,
        definition: CapabilityDefinition,
        input_model: type[BaseModel],
        handler: CapabilityHandler,
    ) -> None: ...

    def get(
        self, name: str
    ) -> tuple[CapabilityDefinition, type[BaseModel], CapabilityHandler] | None: ...

    def list(self) -> Sequence[CapabilityDefinition]: ...


class TransactionStore(Protocol):
    def transaction(self, household_id: UUID | None = None) -> AbstractContextManager[None]: ...
    def close(self) -> None: ...


class InvocationStore(TransactionStore, Protocol):
    def execute_once(
        self,
        namespace: str,
        key: str,
        request_digest: str,
        operation: Callable[[], dict[str, Any]],
    ) -> tuple[dict[str, Any], bool]: ...


class JobStore(TransactionStore, Protocol):
    def create_job(self, job: Job) -> tuple[Job, bool]: ...

    def get_job(self, job_id: UUID) -> Job | None: ...

    def jobs(
        self, household_id: UUID, actor_id: UUID, kind: str, offset: int, limit: int
    ) -> Sequence[Job]: ...

    def jobs_all(self, kind: str, limit: int, status: str = "queued") -> Sequence[Job]: ...

    def project_run_jobs(
        self, household_id: UUID, actor_id: UUID, project_id: UUID,
        before: tuple[datetime, UUID] | None, limit: int,
    ) -> Sequence[Job]: ...

    def project_activity_jobs(
        self, household_id: UUID, actor_id: UUID, project_id: UUID,
        query: str, activity_kind: str | None, before_sequence: int | None, limit: int,
    ) -> Sequence[Job]: ...

    def save_job(self, job: Job, expected_version: int) -> Job: ...

    def transition_job(
        self,
        job_id: UUID,
        expected_version: int,
        status: JobStatus,
        result: dict[str, Any] | None = None,
        error_code: str | None = None,
    ) -> Job: ...


class AuditStore(TransactionStore, Protocol):
    def append_audit(self, event: AuditEvent) -> None: ...

    def audit_events(self, household_id: UUID | None = None) -> Sequence[AuditEvent]: ...


class OutboxStore(TransactionStore, Protocol):
    def add_outbox(self, event: OutboxEvent) -> None: ...

    def outbox_events(self) -> Sequence[OutboxEvent]: ...

    def publish_pending(self, deliver: Callable[[OutboxEvent], None], limit: int = 100) -> int: ...


class IdentityStore(TransactionStore, Protocol):
    def managed_accounts(self) -> Sequence[ManagedAccount]: ...
    def managed_account(self, actor_id: UUID) -> ManagedAccount | None: ...
    def save_managed_account(self, account: ManagedAccount) -> None: ...
    def memberships(self, actor_id: UUID) -> Sequence[Membership]: ...
    def put_membership(self, membership: Membership) -> None: ...
    def delete_membership(self, actor_id: UUID, household_id: UUID) -> None: ...
    def save_session(self, session: Session) -> None: ...
    def get_session(self, token_hash: str) -> Session | None: ...
    def delete_session(self, token_hash: str) -> None: ...
    def revoke_sessions(self, actor_id: UUID) -> None: ...
    def save_enrollment(self, enrollment: Enrollment) -> None: ...
    def get_enrollment(self, token_hash: str) -> Enrollment | None: ...
    def delete_enrollment(self, token_hash: str) -> None: ...
    def save_challenge(self, challenge: Challenge) -> None: ...
    def take_challenge(self, token_hash: str, binding_hash: str) -> Challenge | None: ...
    def passkeys(self, actor_id: UUID) -> Sequence[Passkey]: ...
    def get_passkey(self, credential_id: str) -> Passkey | None: ...
    def save_passkey(self, credential: Passkey) -> None: ...
    def update_passkey(self, credential: Passkey) -> None: ...
    def delete_passkey(self, credential_id: str) -> None: ...
    def password_for_actor(self, actor_id: UUID) -> PasswordCredential | None: ...
    def password_for_username(self, username: str) -> PasswordCredential | None: ...
    def save_password(self, credential: PasswordCredential) -> None: ...


class ConversationStore(TransactionStore, Protocol):
    def recall_documents(
        self,
        household_id: UUID,
        actor_id: UUID,
        terms: tuple[str, ...],
        offset: int,
        limit: int,
        exclude_thread: UUID | None = None,
    ) -> Sequence[RecallDocument]: ...
    def answer_runs(self, thread_id: UUID, offset: int, limit: int) -> Sequence[Run]: ...
    def latest_run(self, thread_id: UUID) -> Run | None: ...
    def save_attempt(self, attempt: ModelAttempt) -> None: ...
    def attempt(self, run_id: UUID) -> ModelAttempt | None: ...
    def pending_attempt(self, thread_id: UUID) -> ModelAttempt | None: ...
    def recent_messages(self, thread_id: UUID, limit: int) -> Sequence[Message]: ...
    def insert_thread(self, thread: Thread) -> None: ...
    def threads(
        self, household_id: UUID, offset: int, limit: int, actor_id: UUID | None = None
    ) -> Sequence[Thread]: ...
    def thread(self, household_id: UUID, thread_id: UUID) -> Thread | None: ...
    def messages(self, thread_id: UUID, after: int, limit: int) -> Sequence[Message]: ...
    def insert_message(self, message: Message) -> None: ...
    def insert_run(self, run: Run, events: tuple[RunEvent, ...]) -> None: ...
    def run(self, run_id: UUID) -> Run | None: ...
    def run_events(self, run_id: UUID) -> Sequence[RunEvent]: ...


class MemoryStore(TransactionStore, Protocol):
    def insert_memory(self, memory: ExplicitMemory) -> None: ...
    def explicit_memories(
        self,
        household_id: UUID,
        offset: int,
        limit: int,
        actor_id: UUID | None = None,
        personal: bool = True,
    ) -> Sequence[ExplicitMemory]: ...
    def explicit_memory(self, household_id: UUID, memory_id: UUID) -> ExplicitMemory | None: ...
    def retract_memory(self, memory: ExplicitMemory) -> None: ...


class InteractionStore(TransactionStore, Protocol):
    def response_preferences(
        self, household_id: UUID, actor_id: UUID
    ) -> ResponsePreferences | None: ...
    def save_response_preferences(
        self, household_id: UUID, actor_id: UUID, preferences: ResponsePreferences
    ) -> None: ...
    def feedback(self, household_id: UUID, actor_id: UUID, run_id: UUID) -> RunFeedback | None: ...
    def save_feedback(self, household_id: UUID, actor_id: UUID, feedback: RunFeedback) -> None: ...


class ConnectedStore(TransactionStore, Protocol):
    def google_connection(self, household_id: UUID, actor_id: UUID) -> GoogleConnection | None: ...
    def google_connections(
        self, household_id: UUID, actor_id: UUID
    ) -> tuple[GoogleConnection, ...]: ...
    def set_default_google_connection(
        self, household_id: UUID, actor_id: UUID, connection_id: UUID
    ) -> None: ...
    def save_google_connection(self, connection: GoogleConnection) -> None: ...
    def delete_google_connection(
        self, household_id: UUID, actor_id: UUID, connection_id: UUID | None = None
    ) -> None: ...
    def save_google_state(self, state: GoogleOAuthState) -> None: ...
    def take_google_state(self, state_hash: str, binding_hash: str) -> GoogleOAuthState | None: ...
    def action(self, action_id: UUID) -> ActionProposal | None: ...
    def recent_actions(
        self, thread_id: UUID, actor_id: UUID, limit: int
    ) -> Sequence[ActionProposal]: ...
    def save_action(self, action: ActionProposal) -> None: ...


class VoiceStore(TransactionStore, Protocol):
    def voice_sessions(self, household_id: UUID, actor_id: UUID) -> Sequence[VoiceSession]: ...
    def voice_session(self, household_id: UUID, session_id: UUID) -> VoiceSession | None: ...
    def save_voice_session(self, session: VoiceSession) -> None: ...




class ProjectArtifactStore(TransactionStore, Protocol):
    def save_project_artifact(self, artifact: ProjectArtifact, content: bytes) -> None: ...
    def project_artifact(self, identifier: UUID) -> tuple[ProjectArtifact, bytes] | None: ...
    def project_artifacts(
        self,
        household_id: UUID,
        actor_id: UUID,
        project_id: UUID | None,
        offset: int,
        limit: int,
    ) -> Sequence[ProjectArtifact]: ...


class ProjectDriveStore(TransactionStore, Protocol):
    def project_drive(
        self,
        household_id: UUID,
        actor_id: UUID,
        project_id: UUID,
    ) -> ProjectDrive | None: ...
    def save_project_drive(self, binding: ProjectDrive) -> None: ...
    def project_file_operation(self, identifier: UUID) -> ProjectFileOperation | None: ...
    def save_project_file_operation(self, operation: ProjectFileOperation) -> None: ...
    def project_file_operations(
        self,
        household_id: UUID,
        actor_id: UUID,
        project_id: UUID,
        limit: int,
    ) -> Sequence[ProjectFileOperation]: ...
    def google_accounts(self) -> Sequence[tuple[UUID, UUID]]: ...


class Store(
    CapabilityStore,
    InvocationStore,
    JobStore,
    AuditStore,
    OutboxStore,
    IdentityStore,
    ConversationStore,
    MemoryStore,
    InteractionStore,
    ConnectedStore,
    VoiceStore,
    ProjectArtifactStore,
    ProjectDriveStore,
    Protocol,
):
    """One transaction boundary for state, audit records, and delivery intents."""
