from __future__ import annotations

from collections.abc import Callable, Sequence
from contextlib import AbstractContextManager
from typing import Any, Protocol
from uuid import UUID

from pydantic import BaseModel

from jarvis.domain.context import ExplicitMemory
from jarvis.domain.conversations import Message, ModelAttempt, Run, RunEvent, Thread
from jarvis.domain.identity import Challenge, Enrollment, Membership, Passkey, Session
from jarvis.domain.models import (
    AuditEvent,
    CapabilityDefinition,
    Job,
    JobStatus,
    OutboxEvent,
)

CapabilityHandler = Callable[[BaseModel], dict[str, Any]]


class CapabilityStore(Protocol):
    def register(
        self,
        definition: CapabilityDefinition,
        input_model: type[BaseModel],
        handler: CapabilityHandler,
    ) -> None: ...

    def get(
        self, name: str
    ) -> tuple[CapabilityDefinition, type[BaseModel], CapabilityHandler] | None: ...

    def list(self) -> Sequence[CapabilityDefinition]: ...


class TransactionStore(Protocol):
    def transaction(self, household_id: UUID | None = None) -> AbstractContextManager[None]: ...


class InvocationStore(TransactionStore, Protocol):
    def execute_once(
        self,
        namespace: str,
        key: str,
        request_digest: str,
        operation: Callable[[], dict[str, Any]],
    ) -> tuple[dict[str, Any], bool]: ...


class JobStore(TransactionStore, Protocol):
    def create_job(self, job: Job) -> tuple[Job, bool]: ...

    def get_job(self, job_id: UUID) -> Job | None: ...

    def transition_job(
        self,
        job_id: UUID,
        expected_version: int,
        status: JobStatus,
        result: dict[str, Any] | None = None,
        error_code: str | None = None,
    ) -> Job: ...


class AuditStore(TransactionStore, Protocol):
    def append_audit(self, event: AuditEvent) -> None: ...

    def audit_events(self, household_id: UUID | None = None) -> Sequence[AuditEvent]: ...


class OutboxStore(TransactionStore, Protocol):
    def add_outbox(self, event: OutboxEvent) -> None: ...

    def outbox_events(self) -> Sequence[OutboxEvent]: ...

    def publish_pending(self, deliver: Callable[[OutboxEvent], None], limit: int = 100) -> int: ...


class IdentityStore(TransactionStore, Protocol):
    def memberships(self, actor_id: UUID) -> Sequence[Membership]: ...
    def put_membership(self, membership: Membership) -> None: ...
    def delete_membership(self, actor_id: UUID, household_id: UUID) -> None: ...
    def save_session(self, session: Session) -> None: ...
    def get_session(self, token_hash: str) -> Session | None: ...
    def delete_session(self, token_hash: str) -> None: ...
    def revoke_sessions(self, actor_id: UUID) -> None: ...
    def save_enrollment(self, enrollment: Enrollment) -> None: ...
    def get_enrollment(self, token_hash: str) -> Enrollment | None: ...
    def delete_enrollment(self, token_hash: str) -> None: ...
    def save_challenge(self, challenge: Challenge) -> None: ...
    def take_challenge(self, token_hash: str, binding_hash: str) -> Challenge | None: ...
    def passkeys(self, actor_id: UUID) -> Sequence[Passkey]: ...
    def get_passkey(self, credential_id: str) -> Passkey | None: ...
    def save_passkey(self, credential: Passkey) -> None: ...
    def update_passkey(self, credential: Passkey) -> None: ...
    def delete_passkey(self, credential_id: str) -> None: ...


class ConversationStore(TransactionStore, Protocol):
    def save_attempt(self, attempt: ModelAttempt) -> None: ...
    def attempt(self, run_id: UUID) -> ModelAttempt | None: ...
    def pending_attempt(self, thread_id: UUID) -> ModelAttempt | None: ...
    def recent_messages(self, thread_id: UUID, limit: int) -> Sequence[Message]: ...
    def insert_thread(self, thread: Thread) -> None: ...
    def threads(self, household_id: UUID, offset: int, limit: int) -> Sequence[Thread]: ...
    def thread(self, household_id: UUID, thread_id: UUID) -> Thread | None: ...
    def messages(self, thread_id: UUID, after: int, limit: int) -> Sequence[Message]: ...
    def insert_message(self, message: Message) -> None: ...
    def insert_run(self, run: Run, events: tuple[RunEvent, ...]) -> None: ...
    def run(self, run_id: UUID) -> Run | None: ...
    def run_events(self, run_id: UUID) -> Sequence[RunEvent]: ...


class MemoryStore(TransactionStore, Protocol):
    def insert_memory(self, memory: ExplicitMemory) -> None: ...
    def explicit_memories(
        self, household_id: UUID, offset: int, limit: int
    ) -> Sequence[ExplicitMemory]: ...
    def explicit_memory(self, household_id: UUID, memory_id: UUID) -> ExplicitMemory | None: ...
    def retract_memory(self, memory: ExplicitMemory) -> None: ...


class Store(
    CapabilityStore,
    InvocationStore,
    JobStore,
    AuditStore,
    OutboxStore,
    IdentityStore,
    ConversationStore,
    MemoryStore,
    Protocol,
):
    """One transaction boundary for state, audit records, and delivery intents."""
